//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameMate.rc
//
#define IDD_GAMEMATE_DIALOG             102
#define IDD_MAIN_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_MENU_TRAY                   128
#define IDD_TAB_GAME_SETTINGS           130
#define IDD_TAB_ACTIVE_PROCESS_TOOLKIT  130
#define IDD_DIALOG_ADDING_TAB           132
#define IDD_DIALOG_ADD_PROCESS_TOOLKIT  132
#define IDD_DIALOG_ACTIONS_EDIT         134
#define IDD_DIALOG_EDIT_ACTIONS         134
#define IDD_DIALOG_BIND_EDIT            137
#define IDD_DIALOG_INPUT_EDITOR         137
#define IDB_PNG_CROSSHAIR               143
#define IDI_ICON1                       144
#define IDB_PNG_CROSSHAIR_0_16          145
#define IDB_PNG_CROSSHAIR_0_24          146
#define IDB_PNG_CROSSHAIR_0_32          147
#define IDB_PNG_CROSSHAIR_1_16          148
#define IDB_PNG_CROSSHAIR_1_24          149
#define IDB_PNG_CROSSHAIR_1_32          150
#define IDB_PNG_CROSSHAIR_2_16          151
#define IDB_PNG_CROSSHAIR_2_24          152
#define IDB_PNG_CROSSHAIR_2_32          153
#define IDB_PNG_CROSSHAIR_3_16          154
#define IDB_PNG_CROSSHAIR_3_24          155
#define IDB_PNG_CROSSHAIR_3_32          156
#define IDB_PNG_CROSSHAIR_4_16          157
#define IDB_PNG_CROSSHAIR_4_24          158
#define IDB_PNG_CROSSHAIR_4_32          159
#define IDB_PNG_CROSSHAIR_5_16          160
#define IDB_PNG_CROSSHAIR_5_24          161
#define IDB_PNG_CROSSHAIR_5_32          162
#define IDB_PNG_CROSSHAIR_6_16          163
#define IDB_PNG_CROSSHAIR_6_24          164
#define IDB_PNG_CROSSHAIR_6_32          165
#define IDB_PNG_CROSSHAIR_7_16          166
#define IDB_PNG_CROSSHAIR_7_24          167
#define IDB_PNG_CROSSHAIR_7_32          168
#define IDB_PNG_CROSSHAIR_8_16          169
#define IDB_PNG_CROSSHAIR_8_24          170
#define IDB_PNG_CROSSHAIR_8_32          171
#define IDB_PNG_ARROW_DOWN              174
#define IDB_PNG_ARROW_UP                175
#define IDD_DIALOG_INPUT_SIMULATOR      177
#define IDD_DIALOG_ACTIONS_EXECUTOR     180
#define IDD_TAB_ACTIONS_EXECUTOR        180
#define IDD_DIALOG_EDIT_MOUSE_MOVE      181
#define IDD_VIEW_EDIT_MOUSE_MOVE        181
#define IDD_DIALOG_EDIT_SCRIPT_PATH     182
#define IDD_VIEW_EDIT_SCRIPT_PATH       182
#define IDD_DIALOG_ADD_ACTION           183
#define IDB_PNG_SETTINGS                184
#define IDD_DIALOG_EDIT_INPUT           184
#define IDD_VIEW_EDIT_INPUT             184
#define IDB_PNG_ADD                     185
#define IDD_VIEW_ACTIONS_EDITOR         185
#define IDB_PNG_DELETE                  186
#define IDB_PNG_CURSOR_POSITION_SELECTION 188
#define IDB_PNG_DELAY                   189
#define IDD_DIALOG_EDIT_NUMBER          190
#define IDD_DIALOG_TIMER                193
#define IDD_DIALOG_TIMER_SETTINGS       195
#define IDB_PNG1                        198
#define IDB_PNG_START_RECORDING         198
#define IDB_PNG_STOP_RECORDING          199
#define IDD_DIALOG_TABLE                202
#define IDC_TABCONTROL_MODES            1000
#define IDC_BUTTON_ADD_TAB              1001
#define IDC_BUTTON_DELETE_TAB           1002
#define IDC_BUTTON_COPY_TAB             1003
#define IDC_BUTTON_RENAME_TAB           1003
#define IDC_SLIDER1                     1004
#define IDC_SLIDER_BRIGHTNESS           1004
#define IDC_EDIT_TAB_NAME               1005
#define IDC_STATIC_TAB_NAME             1006
#define IDC_COMBO_COPY_TAB_SELECTION    1007
#define IDC_STATIC_TAB_NAME2            1008
#define IDC_STATIC_COPY_SETTINGS        1008
#define IDC_CHECK_ENABLED               1009
#define IDC_LIST_MACROSES               1010
#define IDC_BUTTON_ADD                  1011
#define IDC_BUTTON_EDIT                 1012
#define IDC_BUTTON_REMOVE               1013
#define IDC_SETTINGS_GROUP              1014
#define IDC_EDIT_GAME_NAME              1015
#define IDC_MACROSES_GROUP2             1015
#define IDC_MACROSES_GROUP3             1016
#define IDC_BUTTON_RECORD               1017
#define IDC_MACROSES_GROUP4             1017
#define IDC_MACROSES_GROUP5             1018
#define IDC_KEYS_REMAPPING_PLACEHOLDER  1018
#define IDC_MACROSES_PLACEHOLDER        1019
#define IDC_EDIT_ACTION                 1024
#define IDC_EDIT_RANDOMIZE_DELAYS       1024
#define IDC_EDIT_INTERVAL_MIN           1024
#define IDC_EDIT_INTERVAL_SEC           1025
#define IDC_EDIT_INTERVAL_MILLISEC      1026
#define IDC_BUTTON_DELAY_HELP           1028
#define IDC_STATIC_DELAY_HELP           1029
#define IDC_COMBO_EXE_NAME              1030
#define IDC_STATIC_MAUSE_MOVE_HELP      1030
#define IDC_STATIC_CROSSHAIR            1031
#define IDC_STATIC_CROSSHAIR_DEMO       1031
#define IDC_COMBO1                      1032
#define IDC_COMBO_CROSSHAIR_SELECTION   1032
#define IDC_COMBO_INPUT_DRIVER          1032
#define IDC_COMBO_TYPE                  1032
#define IDC_COMBO_SCRIPT                1032
#define IDC_COMBO_RECORD_MODE           1032
#define IDC_COMBO2                      1033
#define IDC_COMBO_CROSSHAIR_SIZE        1033
#define IDC_COMBO3                      1034
#define IDC_COMBO_CONFIGURATION         1034
#define IDC_STATIC_CROSSHAIR_TEXT       1035
#define IDC_MFCCOLORBUTTON_CROSSHAIR_COLOR 1036
#define IDC_STATIC_CROSSHAIR_SIZE       1037
#define IDC_CHECK_USE                   1038
#define IDC_CHECK_SHOW_CROSSHAIR        1038
#define IDC_STATIC_CROSSHAIR_INFO       1039
#define IDC_CHECK_CHANGE_BRIGHTNESS     1040
#define IDC_COMBO_CROSSHAIR_SELECTION2  1041
#define IDC_STATIC_EXE_NAME_INFO        1041
#define IDC_MFCBUTTON1                  1042
#define IDC_MFCBUTTON_INPUT_DRIVER_INFO 1042
#define IDC_MFCBUTTON_SETTINGS          1042
#define IDC_MFCBUTTON_HOTKEY            1042
#define IDC_STATIC_CROSSHAIR_INFO2      1042
#define IDC_STATIC_BRIGHTNESS_INFO      1042
#define IDC_BUTTON_MOVE_UP              1043
#define IDC_MFCBUTTON_TIMER_HOTKEY      1043
#define IDC_BUTTON_MOVE_UP2             1044
#define IDC_BUTTON_MOVE_DOWN            1044
#define IDC_CHECK_PROGRAM_WORKING       1045
#define IDC_BUTTON_EDIT_DELAY           1045
#define IDC_STATIC_NO_TABS              1046
#define IDC_STATIC_INPUT_DRIVER         1047
#define IDC_BUTTON1                     1048
#define IDC_BUTTON_MOUSE_POSITION_SELECT 1048
#define IDC_BUTTON_CHANGE_START_BIND    1048
#define IDC_BUTTON_ACCIDENTAL_PRESS_ADD_CUSTOM 1048
#define IDC_MFCLINK1                    1049
#define IDC_BUTTON_RENAME_CONFIGURATION 1049
#define IDC_BUTTON_RESET                1049
#define IDC_BUTTON_CHANGE_RESET_BIND    1049
#define IDC_STATIC_GROUP                1050
#define IDC_BUTTON_ADD_CONFIGURATION    1050
#define IDC_MFCLINK_RAZER               1051
#define IDC_BUTTON_REMOVE_CONFIGURATION 1051
#define IDC_MFCLINK_LOGITECH_8          1052
#define IDC_MFCLINK3                    1053
#define IDC_MFCLINK4                    1054
#define IDC_MFCLINK5                    1055
#define IDC_MFCLINK6                    1057
#define IDC_MFCLINK_RAZER_7             1057
#define IDC_MFCLINK2                    1058
#define IDC_LIST_ACTIONS                1059
#define IDC_LIST_REMAPPINA              1060
#define IDC_LIST_REMAPPING              1060
#define IDC_RADIO_REPEAT_UNTIL_STOPPED  1061
#define IDC_RADIO_REPEAT_TIMES          1062
#define IDC_EDIT_REPEAT_TIMES           1063
#define IDC_GROUP_REPEAT_INTERVAL       1067
#define IDC_MFCMENUBUTTON_ENABLED       1068
#define IDC_MFCMENUBUTTON2              1069
#define IDC_STATIC_ACTIONS              1072
#define IDC_STATIC_CONFIGURATION        1073
#define IDC_CHECK_ACTIVE_PROCESS_TOOLKIT_ENABLE 1075
#define IDC_STATIC_NO_CONFIGURATION_EXIST 1076
#define IDC_STATIC_NO_CONFIGURATION     1077
#define IDC_BUTTON_ADD_MACROS           1078
#define IDC_BUTTON_REMOVE_MACROS        1079
#define IDC_MFCLINK7                    1080
#define IDC_MFCLINK_LOGITECH_OLD_MORE_INFO 1081
#define IDC_EDIT_MOUSE_POSITION_X       1083
#define IDC_EDIT_MOUSE_POSITION_Y       1084
#define IDC_STATIC_MOUSE_POSITION_X     1087
#define IDC_STATIC_MOUSE_POSITION_Y     1088
#define IDC_STATIC_SCRIPT_PATH          1089
#define IDC_STATIC_                     1090
#define IDC_STATIC_EDITOR               1090
#define IDC_MFCEDITBROWSE               1091
#define IDC_STATIC_INPUT_EDITOR_PLACEHOLDER 1092
#define IDC_STATIC_DESCRIPTION          1093
#define IDC_STATIC_ACTIONS_EDITOR_PLACEHOLDER 1094
#define IDC_CHECK_UNITE_MOVEMENTS       1095
#define IDC_EDIT                        1096
#define IDC_CHECK_USE_DIRECT_INPUT      1097
#define IDC_STATIC_RECORDING_OVERLAY    1098
#define IDC_CHECK_TIMER                 1099
#define IDC_CHECK_START                 1102
#define IDC_STATIC_TIMER                1103
#define IDC_MFCBUTTON_TIMER_SETTIGNS    1104
#define IDC_CHECK_DISPLAY_HOURS         1106
#define IDC_MFCCOLORBUTTON_TEXT         1107
#define IDC_MFCCOLORBUTTON_BACKGROUND   1109
#define IDC_EDIT_START_BIND             1110
#define IDC_OK                          1111
#define IDC_CHECK_HIDE_INTERFACE        1111
#define IDC_EDIT_RESET_BIND             1112
#define IDC_STATIC_START_BIND           1112
#define IDC_STATIC_RESET_BIND           1113
#define IDC_CHECK_RANDOMIZE_DELAY       1113
#define IDC_EDIT_DESCRIPTION            1114
#define IDC_STATIC_DESTRIPTION          1115
#define IDC_STATIC_ACCIDENTAL           1116
#define IDC_COMBO_ACCIDENTAL_PRESS      1117
#define IDC_SPLITTER                    1118
#define IDC_BUTTON_ADD_REMAPPING        1119
#define IDC_BUTTON_REMOVE_REMAPPING     1120
#define IDC_TABLE                       1121
#define IDC_STATIC_GROUP_TITLE          1122
#define ID_ID_ASD                       32771
#define ID_ID_ASD32772                  32772
#define ID_MENU_OPEN                    32773
#define ID_MENU_CLOSE                   32774
#define ID_MENU_ENABLE_TRACES           32775
#define ID_MENU_DISABLE_TRACES          32776
#define ID_MENU_DISABLE_PROGRAM         32777
#define ID_MENU_ENABLE_PROGRAM          32778
#define ID_MENU_ENABLE_PROCESS_TOOLKIT  32779
#define ID_MENU_DISABLE_PROCESS_TOOLKIT 32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
